at 15:31 of 2017-06-02

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,7 +6,7 @@ OS="$(uname -s)"
 echo "
 Are you ready to install po-util?"
 
-read -rp "ENTER / CTRL-C: " || ( echo "\nInstallation aborted.\n" && exit )
+read -rp "ENTER / CTRL-C: " ||  echo "\nInstallation aborted.\n" && exit 
 
 echo "
 Continuing installation...
